//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDamnDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CCOR_AppsDBEntities : DbContext
    {
        public CCOR_AppsDBEntities()
            : base("name=CCOR_AppsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProfessionInfo> ProfessionInfoes { get; set; }
        public virtual DbSet<UserAccountInfo> UserAccountInfoes { get; set; }
    
        public virtual ObjectResult<ProfessionInfo> GetAllProfessionInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProfessionInfo>("GetAllProfessionInfo");
        }
    
        public virtual ObjectResult<ProfessionInfo> GetAllProfessionInfo(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProfessionInfo>("GetAllProfessionInfo", mergeOption);
        }
    }
}
