//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDamnDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountInfo
    {
        public int UserID { get; set; }
        public string UserCode { get; set; }
        public string ProfessionCode { get; set; }
        public string UserName { get; set; }
        public string EMail { get; set; }
        public string PWD { get; set; }
        public string ConfirmPWD { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
